{{- if .Values.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ddns.fullname" . }}-external-public-cname
  labels:
    {{- include "ddns.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "ddns.fullname" . }}-external-public-cname
rules:
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ddns.fullname" . }}-external-public-cname
subjects:
  - kind: ServiceAccount
    name: {{ include "ddns.fullname" . }}-external-public-cname
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "ddns.fullname" . }}-external-public-cname
  apiGroup: rbac.authorization.k8s.io
{{- end }}
